# Load libraries
library("shiny")
library("ggplot2")
library("plotly")

hiv_df <- read.csv("./data/art_coverage_by_country_clean.csv",
                   stringsAsFactors = FALSE

)


bar_chart_df <- hiv_df %>%
  group_by(WHO.Region) %>%
  select(Country, WHO.Region,
         Estimated.ART.coverage.among.people.living.with.HIV...._median) %>%
  filter(Estimated.ART.coverage.among.people.living.with.HIV...._median
         != "NA") %>%
  rename(M_ART_coverage_among_living_HIV =
           Estimated.ART.coverage.among.people.living.with.HIV...._median)

intro <- tabPanel(
  "Intro",
  HTML(
  " <head>
    <meta charset='utf-8'>
    <link rel='preconnect' href='https://fonts.gstatic.com'>
    <link href='https://fonts.googleapis.com/css2?family=Roboto&display=swap' rel='stylesheet'>
    <link rel='stylesheet' href='styles.css'>
    <title>HIV/AIDS and ART Treatment Dataset Introduction</title>
    </head>
    <body>
    <section>
    <img src='hiv.jpg' alt='hand holding up hiv ribbon'>
    <!-- Image taken from https://indianexpress.com/article/lifestyle/life-style/we-need-attention-too-the-plight-of-the-hiv-positive          -community-in-india-4405035/ -->
    <h1>Purpose and Importance of Our Project</h1>
    <p>
    The purpose of our project is to view the extent of treatment coverage for HIV/AIDS in
  countries globally and ART treatment's impact on the number of people living with HIV and compare
        the amount of people living with HIV by region.
      </p>
    </section>

    <section>
      <h2>Source of Dataset</h2>
      <p>
        The data was collected and generated by WHO and UNESCO from their public records
        on the number of people living with HIV/AIDS around the world. Devakumar cleaned
        that data from WHO and UNESCO and put the data into a CSV file that draws a focus
        on treatment statistics for those living with HIV/AIDS by country.
        <a href='https://www.kaggle.com/imdevskp/hiv-aids-dataset'>HIV/AIDS and ART Treatment</a>
      </p>
      <br>
      <p>
        We added another dataset to to add latitude and longitude for all the countries: 
        <a href='https://www.kaggle.com/paultimothymooney/latitude-and-longitude-for-every-country-and-state'>Latitude and longitude</a>
      </p>
      <br>
      <p>
        We added another dataset to track the death rates among all countries to see how certain countries are handling the epidemic: 
        <a href='https://ourworldindata.org/hiv-aids'>Death rates</a>
      </p>
    </section>
  </body>"
))

# Bar chart stuff
bar_chart_page <- tabPanel(
  "Page one",
  h1(strong("Select a Region")),
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "regionselect",
                  label = "Region",
                  selected = "Americas",
                  choices = unique(bar_chart_df$WHO.Region)
      )
    ),
    mainPanel(
      h2("Regional Median Estimated ART Coverage Among People Living with HIV"),
      plotlyOutput(outputId = "region_chart")
    )
  ),
  h2(strong("Chart Summary:")),
  mainPanel(
    textOutput(outputId = "chartexplanation")
  )
)

### Map stuff
# Data for country coordinates
country_coordinates <- read.csv("./data/world_country_coordinate.csv",
                                stringsAsFactors = FALSE)

# combine data
hiv_country <- merge(hiv_df, country_coordinates,
                     by = "Country",
                     all.x = TRUE)

# group_by region
hiv_region <- hiv_country %>%
  drop_na() %>%
  select(
    Country, Estimated.number.of.people.living.with.HIV_median,
    Reported.number.of.people.receiving.ART, WHO.Region, Latitude,
    Longitude
  ) %>%
  filter(Reported.number.of.people.receiving.ART != "Nodata") %>%
  mutate(Reported_receiving_art = strtoi(
    Reported.number.of.people.receiving.ART
  )) %>%
  group_by(WHO.Region) %>%
  summarize(
    total_cases = sum(
      Estimated.number.of.people.living.with.HIV_median,
      na.rm = TRUE
    ),
    total_coverage = sum(Reported_receiving_art, na.rm = TRUE),
    coverage_prop = sum(Reported_receiving_art, na.rm = TRUE) /
      sum(Estimated.number.of.people.living.with.HIV_median,
          na.rm = TRUE),
    avg_lat = mean(Latitude, na.rm = TRUE),
    avg_long = mean(Longitude, na.rm = TRUE)
  )


map_page <- tabPanel(
  "Map",
  fluidPage(
    h2("View Country and Region data on the map")
  )
)

region_selection <- selectInput(
  "region",
  label = h3("Choose a WHO Region"),
  choices = hiv_region$WHO.Region
)

map_chart_page <- tabPanel(
  "Map Chart",
  map_page,
  region_selection,
  h5("Click the marker that appears to view data about your selected region"),
  leafletOutput("region_map")
)

### Line Chart stuff
death_rate_df <- read.csv("./data/deaths-and-new-cases-of-hiv.csv")
death_rate_df <- death_rate_df %>% 
  group_by(death_rate_df$Entity)


country_selection <- selectInput(
  "country",
  label = h3("Choose a Country"),
  choices = unique(death_rate_df$Entity)
)

years_selection <- sliderInput(
  "years", 
  label = h3("Year Range"), 
  min = min(death_rate_df$Year, na.rm = TRUE), 
  max = max(death_rate_df$Year, na.rm = TRUE), 
  value = c(min(death_rate_df$Year, na.rm = TRUE), 
            max(death_rate_df$Year, na.rm = TRUE)),
  sep = "",
  format = "####"
)

chart <- tabPanel(
  "Line Chart",
  fluidPage(
    h2("See How Selected Countries Have Been Dealing with HIV"),
    country_selection,
    years_selection
  )
)

line_chart_page <- tabPanel(
  "Line Chart",
  h1("See How Selected Countries Have Been Dealing with HIV/AIDS"),
  country_selection,
  years_selection,
  plotOutput("linechart")
)



# UI
ui <- 
  navbarPage(
    "HIV Statistics",
    intro,
    bar_chart_page,
    map_chart_page,
    line_chart_page
  )

